### ISSUE TITLE
Failed validation due to ICD Codes

### ISSUE THREAD

**Issue by jorieck** [num-codex/codex-processes-ap1#114]
While performing a stand alone validation, we had multiple issues with the validation of ICD Codes. For every ICD Code we were told that the validation failed without further information or any reason.

In one resource which conforms to the profile 'Stage at diagnosis' of the GECCO dataset (Link: https://simplifier.net/forschungsnetzcovid-19/diagnosiscovid19-duplicate-2) we are using both a SNOMED CT Coding and an ICD Coding:
![sct icd](https://user-images.githubusercontent.com/79310839/200774954-626d1124-5dec-490c-84bd-f5fb6d2b7dc3.PNG)

According to the profile this is allowed:
![profile](https://user-images.githubusercontent.com/79310839/200775203-614a35a8-e8d0-4e66-b0f9-47951e100f65.PNG)

However, after the validation the following error message shows up:
![response](https://user-images.githubusercontent.com/79310839/200775435-b5d23aba-b8cb-4757-8e78-9e37ac4c5641.PNG)

After we removed the ICD Codings, the validation of the resources was successful. 

Is there any explanation why the validation of ICD Codes fails?

**Comment by hhund** [comment]
Hi @riejo,

thank you for reporting this issue. From what I can see so far, validation of `CodeableConcept` elements with multiple `Coding` entries is not fully supported by our validator.

To be more specific, the HAPI validator we are extending is performing the validation of Codings in two steps. The `Coding` is first validated against the `CodeSystem` and then validated against the `ValueSet` if a binding is specified. Since we do not download the complete ICD-10 code-systems but only the `ValueSet`, the offline validation against the `CodeSystem` can not be performed, resulting in the false positive error you are reporting.

**Comment by riejo** [comment]
Hello,

is there any update regarding this bug or when it can be fixed?
Thanks

**Comment by hhund** [comment]
The implementation in #119 removes the dual code checks for CodeSystems: `http://fhir.de/CodeSystem/bfarm/icd-10-gm`, `http://fhir.de/CodeSystem/dimdi/icd-10-gm`, `http://fhir.de/CodeSystem/bfarm/ops` and `http://fhir.de/CodeSystem/dimdi/ops`, `http://fhir.de/CodeSystem/ifa/pzn`. Codes from these systems are only checked against there ValueSets and not against the CodeSystem. We may need to reopen this issue in the future to implement a generalized solution.
